### PR TITLE
mDNS Goodbye packet

### PR DESCRIPTION
**Pull request by mglettig**
Extract from the RFC 6762 (Multicast DNS):
In the case of shared records, a host MUST send a "goodbye"
announcement with RR TTL zero (see Section 10.1, "Goodbye Packets")
for the old rdata, to cause it to be deleted from peer caches, before
announcing the new rdata.

@cpq I created a PR for the goodbye packet.

### CODE REVIEW

**Comment by rojer** [comment]
@mglettig does this mean that every advertisement should be preceded by a goodbye? or does it mean that if anything changes in the advertisement, a goodbye with old data and TTL=0 should be sent?

**Comment by mglettig** [comment]
@rojer 
Thank you for looking into my PRs. I do send the goodbye packet right before a clean shutdown. This is another extract from the RFC 6762:
> "In the case where a host knows that certain resource record data is
> about to become invalid (for example, when the host is undergoing a
> clean shutdown), the host SHOULD send an unsolicited Multicast DNS
> response packet, giving the same resource record name, rrtype,
> rrclass, and rdata, but an RR TTL of zero. This has the effect of
> updating the TTL stored in neighboring hosts' cache entries to zero,
> causing that cache entry to be promptly deleted."

The other case for the goodbye packet is the update of the rdata for shared records (extract from RFC 6762).
> "In the case of shared records, a host MUST send a "goodbye"
> announcement with RR TTL zero (see Section 10.1, "Goodbye Packets")
> for the old rdata, to cause it to be deleted from peer caches, before
> announcing the new rdata. In the case of unique records, a host
> SHOULD omit the "goodbye" announcement, since the cache-flush bit on
> the newly announced records will cause old rdata to be flushed from
> peer caches anyway."

**Comment by rojer** [comment]
@mglettig hey, what do you know, sometimes actually reading the RFC helps :)
ok, i see. it makes sense. it sounds, like there is a specific case where this should be done - on clean shutdown. so instead of making it a public API, i'd rather we'd just do it in reboot hook.
would that suit you?

**Comment by mglettig** [comment]
Hi @rojer 
Thanks for the suggestion with the reboot hook. That would be perfect. But please make sure it is also sent before entering deep sleep mode.

For the 2nd use case (shared records) a public method would be needed. We don't use shared records so it's up to you if you want to add a public method in addition to the reboot / deep sleep hook.

Regards,
Michael

**Comment by rojer** [comment]
ok, i see. since we don't control deep sleep API currently, let's go with adding public API so you can do it yourself.
please rebase the PR, resolve conflicts and i'll integrate.

**Comment by mglettig** [comment]
@rojer I updated the PR.

**Comment by rojer** [comment]
@mglettig ok, integration PR sent. i tweaked it a bit - renamed function to `mgos_dns_sd_goodbye()`. otherwise, no changes. i'll make a note to look into making mos send a goodbye packet on reboot automatically. it's not quite trivial, so it'll need to wait.

**Pull request closed without merging**
